### ISSUE TITLE
Error 500 merging 2014 Euros candidate

### ISSUE THREAD

**Issue by sjorford** [DemocracyClub/yournextrepresentative#1007]
Merging these two gives a `500` error:
https://candidates.democracyclub.org.uk/person/69882/marc-scheimann
https://candidates.democracyclub.org.uk/person/5822/marc-scheimann

Doesn't appear to be the same as #936 - there are no conflicting `standing_in` values

**Comment by symroe** [comment]
Sentry issue: [YNR-V9-FB](https://sentry.io/organizations/democracy-club-gp/issues/991987035/?referrer=github_plugin)

**Comment by symroe** [comment]
The problem here is that the same value exists for two different identifier types `Facebook Page` and `Facebook Personal`. Identifiers are unique on `(person, value)`, and the merge doesn't deal with this case. 

I'll fix that, but for the moment the easy "fix" is to change the two Facebook links to be the same type, and the merge will work.
