### ISSUE TITLE
Sideways photos

### ISSUE THREAD

**Issue by sjorford** [DemocracyClub/yournextrepresentative#1009]
These candidates all have photos that are rotated sideways:
https://candidates.democracyclub.org.uk/person/9677/eunice-christine-brockman
https://candidates.democracyclub.org.uk/person/10428/meenakshi-minnis
~https://candidates.democracyclub.org.uk/person/43423/fleur-anderson~
https://candidates.democracyclub.org.uk/person/48242/andy-walker
https://candidates.democracyclub.org.uk/person/53277/patrick-david-keating
https://candidates.democracyclub.org.uk/person/53924/blue-cooper
https://candidates.democracyclub.org.uk/person/54706/sandra-elizabeth-daniells
https://candidates.democracyclub.org.uk/person/61573/bryan-martin-james-hillman

![image](https://user-images.githubusercontent.com/10633357/64163659-96cd3780-ce39-11e9-8439-5b561e36d849.png)

Presumably the original photos had orientation information, that displays correctly in the cropping interface, but is then being discarded

These can be fixed manually by downloading the cropped image, rotating and reuploading to the queue - e.g. https://candidates.democracyclub.org.uk/person/11898/danielle-kail

**Comment by jf1** [comment]
2 thoughts...
They may have been displayed sideways in the cropping interface... Sometimes I've approved a rotated photo when the candidate has repeatedly uploaded them (and they are displayed correctly in other apps) and I don't have time to fix them manually. IIRC it's sometimes displayed sideways in the cropping interface but is ok when displayed on WCIVF etc, hence me starting to let them through.
Rather than manually fix those candidates I'd much rather the underlying issue is fixed, either by enabling manual rotation in the cropping interface, or by fixing the system that reads/processes the rotation information. There are links to a library that fixed the same issue on another site, in https://github.com/mysociety/yournextrepresentative/issues/286

**Comment by annapowellsmith** [comment]
These are all rotated too (sorry, don't have time to match to candidate IDs, some may duplicate list above):

```
img url 3 South Derbyshire 6560-dc0388c6-6a8c-4221-b59f-183b5485b119.png
img url 2 Ellesmere Port and Neston 6898-604db163-2fd4-4782-8739-d0c8b8121cea.png
img url 2 North Herefordshire North Herefordshire 34585-d562654f-1c11-4e2b-850b-5a8044a4b8ea.png
img url 6 Brent North 48143-ee5bb501-1975-4ef4-a5ad-0bd46cf39e9d.png
img url 2 Somerton and Frome 71627-bbdee464-911c-4d13-b1e2-dfc2a8a6ee8a.png
img url 3 Makerfield 72465-98e77bf8-f280-4924-9e7a-637d3497c33c.png
img url 6 Edingburgh South West 72567-153c90d6-1e47-4b5d-9992-fd1b83262375.png
img url 6 Edmonton 72590-122afbef-98e9-4316-b1d5-0f3326fcc0f4.png
```

**Comment by pmk01** [comment]
I *think* the sideways image issue has been fixed - I haven't seen one for a while, anyway. Regardless, an option to rotate photos in the edit view would be useful.

Also, the above photos need manually rotating, which I will try to do at some point unless someone gets there before me.
