### ISSUE TITLE
Move review required logic to LoggedAction model

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/yournextrepresentative#1010]
We currently work out if an edit needs review by:

1. [Get QS `LoggedAction`s with a slice/filter (edits in the last day, by default)](https://github.com/DemocracyClub/yournextrepresentative/blob/master/ynr/apps/candidates/feeds.py#L99-L107)
2. [Pass that QS to a list of functions](https://github.com/DemocracyClub/yournextrepresentative/blob/master/ynr/apps/candidates/models/db.py#L28-L34)
3. [Each function works out if a condition is met, and returns a list of logged actions that meet the condition](https://github.com/DemocracyClub/yournextrepresentative/blob/master/ynr/apps/candidates/models/needs_review.py#L16)

All of this is done for each request to the needs review RSS feed.

There are some limitations to this:

1. The view is doing a lot of work, repeated a lot in the quiet times and then overloaded in the busy times (when we have a SOPN party with >1,000 edits an hour, for example)
2. It's tricky to generate the same list somewhere else, like on a list of edits that need review on the website
3. There ends up being a lag when posting edits to Slack, because the RSS feed isn't instant

If we move to a model of marking a `LoggedAction` as needing review _at the point it's created_ (e.g. when the edit is made) then we can:

1. Make the feed more efficient 
2. Create a list of those edits on the website
3. Post to Slack as soon as their created

This would require some more fields on the `LoggedAction` model, but the basic logic would be more or less the same as at the moment.

**Comment by chris48s** [comment]
Big :+1: to this. Storing a flag on the record also has the advantage that we can mark the record as "reviewed" once someone has looked at it, which we also can't really do at the moment (beyond slack emoji reaction).

I think its worth thinking of this as an Enum/'status code' type field, so the possible values are like:

- no review needed (default)
- edit to statement
- edit to person liable to vandalism
- one of first edits of new user
- reviewed: ok
- reviewed: needs folllow up/escalated to admin
.. other statuses can be added in future

Broadly: lets get it done sooner rather than later. We don't necessarily need to have the front-end to set "reviewed" statuses for an MVP.

Also anything we can do to cut down the volume needing review (e.g: edits by bots never need moderation) is going to be valuable here.

**Comment by symroe** [comment]
Calling this closed as per #1012
