### ISSUE TITLE
Party candidate counts (in party select) aren’t meaningful

### ISSUE THREAD

**Issue by andylolz** [DemocracyClub/yournextrepresentative#115]
![screen shot 2017-04-21 at 13 20 17](https://cloud.githubusercontent.com/assets/464193/25277136/5f8e1f8a-2695-11e7-8f6d-5ebd9470ad7c.png)

I guess these numbers show either candidates per party, or candidates per party for current elections?

It would be better to show candidates per party for the election I am currently adding.

**Comment by mhl** [comment]
It's the total candidates for that party across all the *current* elections we running at the moment, so those totals include the candidate counts from all the local elections. The logic for deciding which counts to use and when is here: https://github.com/DemocracyClub/yournextrepresentative/blob/5e02f07ae5ca66ecb7d787b50334d61813b79e5f/candidates/models/popolo_extra.py#L735-L776

When we added this, the reason for adding the number of candidates was primarly to make it obvious to people why the list had that ordering, so people wouldn't think we were ordering them by hand, which would be subject to bias, etc. etc. I think that's its value rather than the numbers themselves being useful to people.

**Comment by andylolz** [comment]
Aha! Thanks Mark – I’d forgotten the reason for this.

Okay I think this is probably closable then. I do find these counts a biiit weird still… I think I’d rather they were per election. But not a big issue.
