### ISSUE TITLE
Cannot add details to candidate in Orkney - North Isles by election

### ISSUE THREAD

**Issue by sweynh** [DemocracyClub/yournextrepresentative#1218]
Trying to "Add or Edit"add to add email address and FB page link to candidate Heather Woodbridge.  https://candidates.democracyclub.org.uk/person/72883/update 

Error when trying to save changes:
"Oops!
We could not accept some of the changes you made.

Please check your information matches our requirements, below."

 Scrolling down to the Post field, "North Isles" has been deleted (I didn't even tab into the field), and raised this error message:
"Can't delete a membership of a locked ballot (local.orkney-islands.north-isles.by.2020-10-01)"

**Comment by symroe** [comment]
Thank you for reporting, and for trying to add details!

Sorry about the error - can you tell me a bit more about the device / browser you're using?

**Comment by sweynh** [comment]
Thanks for quick response.

Here are details requested:

HP laptop 14-bp0xx
OS build: 19041.50
Win Feature Exp. Pack: 120.2212.31.0

Chrome browser
Version 84.0.4147.135 (Official Build) (64-bit)

**Comment by sjorford** [comment]
FYI I get the same

![image](https://user-images.githubusercontent.com/10633357/91836324-82856b80-ec42-11ea-9b47-952d656d598d.png)

**Comment by symroe** [comment]
This was a bit tricky, and came about by me marking locked ballots as disabled in HTML.

Turns out the testing stack will submit disabled form elements, but browsers don't. This means the site thought users were trying to delete candidacies, when actually it was just the browser ignoring the fields.

I've now removed the candidacy form for ballots that are locked.
