### ISSUE TITLE
Ballots can't be unique on (post,election)

### ISSUE THREAD

**Issue by sjorford** [DemocracyClub/yournextrepresentative#1346]
I added the four South Lakeland by-elections to EE based on https://www.southlakeland.gov.uk/voting-and-elections/elections/casual-vacancies-and-postponed-elections/#gsc.tab=0

So there are now new IDs in EE for the by-elections, which differ from the cancelled scheduled elections:
`local.south-lakeland.broughton-coniston.2021-05-06` (cancelled)
`local.south-lakeland.broughton-coniston.by.2021-05-06` (by-election)

The election group `local.south-lakeland.2021-05-06` no longer shows as cancelled on https://elections.democracyclub.org.uk/elections/local.2021-05-06/ whereas the other 5 cancelled elections do (Cumbria, North Yorkshire etc.)

But the by-election IDs are not showing on https://candidates.democracyclub.org.uk/elections/local.south-lakeland.2021-05-06/ and can't be selected on candidate pages
![image](https://user-images.githubusercontent.com/10633357/110327808-5e9c4b80-8012-11eb-843b-a53e41b5b478.png)

**Comment by symroe** [comment]
Chris is right that this is the issue.

Question is, do we still need the unique constraint on `Ballot`? This was here because previously a lot of things were keyed of `(post, election)`, like URLs for example. We've _mostly_ moved to using `Ballot` as the key, but there will be places where this isn't true, and it might be hard to work this out.

**Comment by chris48s** [comment]
> Question is, do we still need the unique constraint on Ballot?

I mean.. assuming that is a non-rhetorical question: There are definitely still a non-zero number of URLs that expect election/post to be unique e.g:
https://github.com/DemocracyClub/yournextrepresentative/blob/bd0db75e46ef27efb2d2f459087f26f5e03cba21/ynr/apps/candidates/urls.py#L22-L31
and a non-zero number of places where this constraint is assumed at the DB level too e.g:
https://github.com/DemocracyClub/yournextrepresentative/blob/a299396941d0177093124c443158469fa225a0b9/ynr/apps/candidates/models/db.py#L110
so it is needed in the sense that there is still code that breaks if you just remove the constraint.. but it isn't _needed_ in the sense that AFAIK it was always a (not yet fully achieved) objective to get to a stage where YNR's data model reflects EE's data model rather than the popolo-based origins and ballot_id is the canonical ID for a ballot rather than post/election.
