### ISSUE TITLE
Photos not cropping properly

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/yournextrepresentative#1381]
![Screenshot 2021-03-27 180508](https://user-images.githubusercontent.com/61510609/112804676-96743d00-906c-11eb-823a-7aa050ca7699.png)

This is becoming more common, and seems to affect photos uploaded by first-time users (ie. candidates, probably from their phones?). The photo cropper goes awry as shown.

**Comment by pmk01** [comment]
![Screenshot 2021-04-07 194413](https://user-images.githubusercontent.com/61510609/113917909-b973bf00-97d9-11eb-9a88-e65a8b21f173.png)

https://candidates.democracyclub.org.uk/person/75064

**Comment by jf1** [comment]
Stuart and I have noticed a new issue where (we think) the EXIF data isn't correctly handled by the image cropping library, so although your cropping looks ok on screen the result is a misplaced crop and poor output.

We noticed that the the image previews in Slack can be stretched, suggesting that it can also have the same problem, eg:
From https://candidates.democracyclub.org.uk/moderation/photo/review/23843
https://static-candidates.democracyclub.org.uk/media/queued-images/2021/04/09/75680-ad914ccc-354a-4bd6-90b1-5cfad76226b4.jpg
![image](https://user-images.githubusercontent.com/4711363/114262154-5c912800-99d6-11eb-9afd-2457fbc59af4.png)

**Comment by jf1** [comment]
Another example where a candidate has uploaded again following the cropping issue https://candidates.democracyclub.org.uk/moderation/photo/review/24086

**Comment by jf1** [comment]
Another one https://candidates.democracyclub.org.uk/moderation/photo/review/24093
If you re-moderate this (please untick "Make this the primary image of the candidate?") then you'll see how the cropping loses its alignment.

**Comment by pmk01** [comment]
This candidate when viewed via admin: https://candidates.democracyclub.org.uk/person/61511

**Comment by jf1** [comment]
More examples (please untick "Make this the primary image of the candidate?" if you re-moderate)
https://candidates.democracyclub.org.uk/moderation/photo/review/24629
https://candidates.democracyclub.org.uk/moderation/photo/review/24682
https://candidates.democracyclub.org.uk/moderation/photo/review/24692

**Comment by pmk01** [comment]
I don't re-moderate, it's an issue with the image. I screenshot it, upload the screenshot, and moderate that.

**Comment by jf1** [comment]
The re-moderation suggestion was for anyone looking into the cause and a fix - I don't know if dev environments have access to the photo upload queue.

If you're happy to manipulate it manually you can get the original image from the `reverse image search` link.

A few more for reference...
https://candidates.democracyclub.org.uk/moderation/photo/review/24869
https://candidates.democracyclub.org.uk/moderation/photo/review/24976
https://candidates.democracyclub.org.uk/moderation/photo/review/24977

**Comment by jf1** [comment]
Some more examples below. I was able to sort the first two in the UI but this isn't possible with the last two (same photo, re-uploaded) due to the aspect ratio, so cc @pmk01 in case you want to contact the candidate or deal with it manually.
https://candidates.democracyclub.org.uk/moderation/photo/review/25667
https://candidates.democracyclub.org.uk/moderation/photo/review/25855
https://candidates.democracyclub.org.uk/moderation/photo/review/25929
https://candidates.democracyclub.org.uk/moderation/photo/review/25945

**Comment by jf1** [comment]
Here's the latest batch of examples. I think most have been cropped to an acceptable standard, even if they're not all perfect.
Seems the issue is (at least sometimes) that the cropping geometry has a 90 degree CCW rotation compared to what we see in the UI.
https://candidates.democracyclub.org.uk/moderation/photo/review/25959
https://candidates.democracyclub.org.uk/moderation/photo/review/25961
https://candidates.democracyclub.org.uk/moderation/photo/review/26002
https://candidates.democracyclub.org.uk/moderation/photo/review/26059
https://candidates.democracyclub.org.uk/moderation/photo/review/26150
https://candidates.democracyclub.org.uk/moderation/photo/review/26287
https://candidates.democracyclub.org.uk/moderation/photo/review/26349
https://candidates.democracyclub.org.uk/moderation/photo/review/26366
https://candidates.democracyclub.org.uk/moderation/photo/review/26372
https://candidates.democracyclub.org.uk/moderation/photo/review/26380
https://candidates.democracyclub.org.uk/moderation/photo/review/26408
https://candidates.democracyclub.org.uk/moderation/photo/review/26415
https://candidates.democracyclub.org.uk/moderation/photo/review/26418
https://candidates.democracyclub.org.uk/moderation/photo/review/26453

**Comment by jf1** [comment]
Hopefully this is the last batch to report. The last one can't be done properly in the UI but it's been cropped to show the face ok.
https://candidates.democracyclub.org.uk/moderation/photo/review/26666
https://candidates.democracyclub.org.uk/moderation/photo/review/26788
https://candidates.democracyclub.org.uk/moderation/photo/review/26795
https://candidates.democracyclub.org.uk/moderation/photo/review/26799
https://candidates.democracyclub.org.uk/moderation/photo/review/26814
https://candidates.democracyclub.org.uk/moderation/photo/review/26815
https://candidates.democracyclub.org.uk/moderation/photo/review/26820
https://candidates.democracyclub.org.uk/moderation/photo/review/26907
https://candidates.democracyclub.org.uk/moderation/photo/review/26925
https://candidates.democracyclub.org.uk/moderation/photo/review/26930
https://candidates.democracyclub.org.uk/moderation/photo/review/26977
https://candidates.democracyclub.org.uk/moderation/photo/review/26980

**Comment by sjorford** [comment]
Another where the cropping went wrong
https://candidates.democracyclub.org.uk/moderation/photo/review/27258
![image](https://user-images.githubusercontent.com/10633357/125487702-2486f00e-2661-4ce7-8c44-7097203444fa.png)

I think the image size is part of the issue - this one is 12 megapixels. I've shrunk it in good ol' MS Paint and re-uploaded

**Comment by sjorford** [comment]
A marginal case here: https://candidates.democracyclub.org.uk/moderation/photo/review/27577

This is how I cropped it:
![image](https://user-images.githubusercontent.com/10633357/142903439-44ac3d28-6551-42ea-8628-1e40b29a0bf0.png)

And this is how it ended up - it has been shifted by about 10%:
![image](https://user-images.githubusercontent.com/10633357/142903479-a7efb56f-e7c5-4c04-89e8-8fe69bb287a5.png)

The source image is 3000x4000 pixels - it doesn't display properly in the Firefox console which may be due to its size:
![image](https://user-images.githubusercontent.com/10633357/142903651-cd09bd93-1169-4018-beee-8c1f229f49e5.png)

**Comment by pmk01** [comment]
In case it's not mentioned elsewhere, a method of returning to the cropping page would be super useful. Often the process is:
 - crop photo
 - close window
 - discover a couple of hours later that the photo hasn't cropped properly
 - no way back to cropping page
 - 😢

**Comment by VirginiaDooley** [comment]
Closed with https://github.com/DemocracyClub/yournextrepresentative/pull/1776
