### ISSUE TITLE
Server Error (500) for "Not standing again"

### ISSUE THREAD

**Issue by hugovk** [DemocracyClub/yournextrepresentative#143]
https://candidates.democracyclub.org.uk/election/parl.2017-06-08/post/WMC:E14001059/wythenshawe-and-sale-east

1. Click "Not standing again" for Jess Mayo or Johnny Disco
2. Enter a reason: "Standing in Gorton instead [and one the reference URLs below]"
3. Click "Save changes"

Expected result: saves data and updates candidates

Actual result: Server Error (500)

![image](https://cloud.githubusercontent.com/assets/1324225/25438521/793fbb3a-2aa2-11e7-9806-0b1c26d5af7f.png)

References: 
* https://twitter.com/johnnydisco1980/status/856968169721917440
* https://twitter.com/Greens_JessMayo/status/857226360930131970

**Comment by hugovk** [comment]
Console says:

`POST https://candidates.democracyclub.org.uk/election/parl.2017-06-08/candidacy/delete 500 (INTERNAL SERVER ERROR)` `delete:1`

**Comment by mhl** [comment]
Thanks for reporting this, @hugovk, and sorry about the inconvenience.

The exception this has triggered is actually really helpful, though, because it's from an assertion I added some time ago to help track down how some inconsistent data mysteriously appeared in the database. This was introduced in 4c1724fdc9f53abd (with reference to the commit message of 0984194). The line with the assertion that's failing is: https://github.com/DemocracyClub/yournextrepresentative/blob/1912f17d26c6b8f74625ed6f4ef9cc56a7dd040a/candidates/views/candidacies.py#L119

To take the example of Johnny Disco, since he has the most memorable name, before clicking on "Not standing again?" he has the following `Membership` data (output reformatted to add line breaks):

```
In [1]: p = Person.objects.get(name='Johnny Disco')

In [3]: for m in p.memberships.all():
    print 'post: {post} ({post_id}, post.extra.elections.all(): {elections}, membership.extra.election: {election}'.format(post=m.post, post_id=m.post.extra.slug, elections=m.post.extra.elections.all(), election=m.extra.election)
   ...:     
post: Assembly Member for North Wales (gss:W10000001, post.extra.elections.all(): [<Election: 2016 Welsh Assembly Election (Regions)>], membership.extra.election: 2016 Welsh Assembly Election (Regions)
post: Northenden ward (MTW:E05000712, post.extra.elections.all(): [<Election: Manchester local election>], membership.extra.election: Manchester local election
post: Manchester, Gorton (WMC:E14000808, post.extra.elections.all(): [<Election: 2017 General Election>, <Election: Manchester, Gorton>], membership.extra.election: 2017 General Election
post: Manchester, Gorton (WMC:E14000808, post.extra.elections.all(): [<Election: 2017 General Election>, <Election: Manchester, Gorton>], membership.extra.election: Manchester, Gorton
post: Member of Parliament for Wythenshawe and Sale East (65669, post.extra.elections.all(): [<Election: 2015 General Election>, <Election: 2010 General Election>], membership.extra.election: 2015 General Election

In [4]: p.extra.not_standing.all()
Out[4]: []
```

To particularly note here is the current candidacy for the post `WMC:E14000808` (Manchester Gorton) in the 2017 General Election (`parl.2017-06-08`). (He is also marked as a candidate in the (now-cancelled) Manchester Gorton by-election which would have happened right after the 2017 General Election. That is fine, though.)

The important point is that that's a different post from the one of the page that we're looking at, which is for `WMC:E14001059` (Wythenshawe and Sale East). So clicking "not standing again" on that page triggers the POST to https://candidates.democracyclub.org.uk/election/parl.2017-06-08/candidacy/delete with a post_id parameter of `WMC:E14001059`. (He is shown as a candidate of unknown status on that page because he stood in Wythenshawe and Sale East in 2010 and 2015.)

The `CandidacyDeleteView` removes any candidacy of Wythenshawe and Sale East in the Election before trying to add the election to `not_standing`, but *only* that candidacy.

The `check_no_candidancy_for_election` then fails because it's checking that there's a candidacy for that election still present before adding it to the `not_standing` list for that candidate.

So what's the problem here? You could look at it one of two ways:
1. The `not_standing` relation on `PersonExtra` is broken, because it broadly states someone's not standing in an `Election` at all, rather than not standing in for a particular `Post` / `Election` combination - it could refer to a `PostExtraElection`s instead. Changing to this alternative would be more expressive, and *perhaps* better matches what most people will mean when they click on "Not standing again?", I think - that they're not standing again *for that seat* in that election.
2. The `CandidacyDeleteView` should remove all candidacies of an `Election` when someone clicks on `Not standing again` - it currently [only removes the `Membership`s for that particularly `Post` / `Election` combination](https://github.com/DemocracyClub/yournextrepresentative/blob/1912f17d26c6b8f74625ed6f4ef9cc56a7dd040a/candidates/views/candidacies.py#L113-L117). If we take that approach, we should also make sure that candidates who have a candidacy of *any* post in an election never appear in the "Is a candidate from an earlier election standing again?" section of any post in that election, since moving from standing in one constituency to another between general elections is common, and we don't want someone removing their new candidacy thinking that they're just saying they're not standing again in the old constituency again.

**Comment by JoeMitchell** [comment]
Another place this is happening (if it's in anyway useful to know!)

>On the basis of http://www.ukip-dbs.org.uk/, I'm trying to set Mark Thackray as "not standing" in the 2017 General Election. Steps I'm taking:

>* Start from https://candidates.democracyclub.org.uk/election/parl.2017-06-08/post/WMC:E14000666/dewsbury
>* Click on "Not standing again" next to Thackray
>* Fill in "http://www.ukip-dbs.org.uk/" in the information box
>* Press "Save Changes"

>I then get a 500 Server Error at https://candidates.democracyclub.org.uk/election/parl.2017-06-08/candidacy/delete :-(
