### ISSUE TITLE
Photo moderation page 5825 causes 500 server error

### ISSUE THREAD

**Issue by jf1** [DemocracyClub/yournextrepresentative#145]
https://candidates.democracyclub.org.uk/moderation/photo/review/5825

**Comment by mhl** [comment]
This is happening because that "image" uploaded by the Twitter avatar importer command is actually an HTML file (a 404 page from Twitter). The `candidates_add_twitter_images_to_queue` command should check that the image file is of a known image type (as the manual uploading process does) to avoid this. (And we should remove any such non-images that have been imported by that job.)

**Comment by mhl** [comment]
I've removed all the obviously broken "images" from the image moderation queue now, and once #146 is merged, it shouldn't arise again.

**Comment by jf1** [comment]
Thanks @mark. You're welcome to close this now or when the merge is done.

**Comment by jf1** [comment]
Ooh, I can close...

**Comment by jf1** [comment]
Please can an admin delete the 6 'photos' in the moderation queue from April 28, 2017 ? They all give a 500 server error and previously this was because they weren't image files.

As @mhl removed files on April 27 I wonder if the April 28 files were imported before the updated script was in place. I've not been aware of any 500 errors form imports done after April 28

**Comment by mhl** [comment]
I've removed the bad images from that period now, so hopefully these errors won't reoccur.
