### ISSUE TITLE
Results problem

### ISSUE THREAD

**Issue by pmk01** [DemocracyClub/yournextrepresentative#1455]
I've entered the results for this area, but it's not set a winner: https://candidates.democracyclub.org.uk/elections/parl.uxbridge-and-south-ruislip.2017-06-08/

Johnson is labelled marked as not elected.

**Comment by sjorford** [comment]
I think this is because there's no number of seats contested on https://elections.democracyclub.org.uk/elections/parl.uxbridge-and-south-ruislip.2017-06-08/

Possibly related: https://elections.democracyclub.org.uk/elections/parl.2017-06-08/ currently throws a "Whoops!", as do other `parl.` pages such as https://elections.democracyclub.org.uk/elections/parl.2021-05-06/

**Comment by sjorford** [comment]
Had the same issue here: https://candidates.democracyclub.org.uk/elections/local.rotherham.brinsworth-and-catcliffe.2016-05-05/

There were three winners set, but the results had been entered in the wrong order. I corrected the vote figures, but it didn't change the winners. I unset the winners but now can't set the new winners. All the candidate pages are showing "Not elected", e.g. https://candidates.democracyclub.org.uk/person/18368/nigel-simpson

![image](https://user-images.githubusercontent.com/10633357/116045615-1b517700-a66a-11eb-9411-c65349529988.png)

**Comment by VirginiaDooley** [comment]
<figure class="video_container">
 <iframe src="https://drive.google.com/file/d/1vwEHSkXqTDrQyrOAx-ALEpxG2aPXNoVk/preview" width="640" height="480"></iframe>
</figure>
