### ISSUE TITLE
Can't enter some results

### ISSUE THREAD

**Issue by sjorford** [DemocracyClub/yournextrepresentative#1510]
Some results URLs produce a "Not found" error, e.g.
https://candidates.democracyclub.org.uk/uk_results/parl.upper-bann.2017-06-08/
https://candidates.democracyclub.org.uk/uk_results/local.rotherham.brinsworth-and-catcliffe.2016-05-05/

**Comment by michaeljcollinsuk** [comment]
@symroe this is due to limiting the results view to only FPTP elections. https://github.com/DemocracyClub/yournextrepresentative/pull/1492 will have helped with this, but it won't be updating older elections like these. Can I run the "full" `uk_create_elections_from_every_election` management command on the server as a one off?

**Comment by michaeljcollinsuk** [comment]
Actually a full import isn't necessary, I update the relevant elections in a shell

**Comment by michaeljcollinsuk** [comment]
I have re-run a full import - results page can now be accessed for both the examples given. If we come across others where we should be able to enter results but can't, this is likely to be due to missing data in EE. But for now I'll close this issue
