### ISSUE TITLE
Mising data in JSON response to request for constituency info.

### ISSUE THREAD

**Issue by pperrin** [DemocracyClub/yournextrepresentative#222]
I was using this URL to get candidates for Brighton Kemptown in the upcoming general election, but the response seems to be missing all the info about this election. https://candidates.democracyclub.org.uk/api/v0.9/posts/65844/

**Comment by mhl** [comment]
@pperrin I'm sorry about this but the API docs haven't been updated since the 2015 election, and actually the post IDs have been changed since then. I hope I'll get time to up date them today (there's a ticket for that here: #232)

In the mean time, this email will give you details on how to find (or migrate to) the new post IDs: https://groups.google.com/forum/#!msg/democracy-club/0pu2wmlmyIE/r2ZU8WIHBQAJ

If you want to find the post ID from MapIt, then in a postcode lookup like https://mapit.mysociety.org/postcode/SW1A1AA you can go through the objects in `areas` until you get to one with type `WMC` and then get the GSS code from `codes.gss` in that area.

Then the post ID on https://candidates.democracyclub.org.uk/ would be `WMC:E14000639` in that example.

Sorry again about the inconvenience, and our delay in replying - it's been a frantic time since the election was called.

**Comment by symroe** [comment]
> If you want to find the post ID from MapIt, then in a postcode lookup like https://mapit.mysociety.org/postcode/SW1A1AA you can go through the objects in areas until you get to one with type WMC and then get the GSS code from codes.gss in that area.

Or this page will give you the mappings between all the IDs in one go, if that's useful for your application https://mapit.mysociety.org/areas/WMC
