### ISSUE TITLE
(In)correct number of candidates for 2017 General Election?

### ISSUE THREAD

**Issue by PeteDevoy** [DemocracyClub/yournextrepresentative#267]
Trying to work out how many candidates there are in total...

In [the CSV](https://candidates.democracyclub.org.uk/media/candidates-parl.2017-06-08.csv) there are **3304**

The BBC [election site](http://www.bbc.co.uk/news/election-2017-39946901) says there are **3307** but when I scraped it I got **3306**

**Comment by chris48s** [comment]
The BBC are incorrectly listing two withdrawn candidates:

Brentford & Isleworth:
* http://www.bbc.co.uk/news/politics/constituencies/E14000593
* https://www.hounslow.gov.uk/download/downloads/id/853/brentford_and_isleworth.pdf

Bury St Edmunds:
* http://www.bbc.co.uk/news/politics/constituencies/E14000613
* http://www.westsuffolk.gov.uk/Council/Voting_and_Elections/upload/Statement-of-Persons-Nominated-Notice-of-Poll-and-Situation-of-Polling-Stations-Bury-St-Edmunds-constituency.pdf

They were also previously showing a withdrawn candidate in Wolverhampton South East, but this has now been corrected and their list matches the SOPN ( http://www.wolverhampton.gov.uk/CHttpHandler.ashx?id=12855&p=0 ).

My guess would be that they didn't update their total when they fixed Wolverhampton South East which is why they report the total as 3,307 but are listing 3,306 candidates.

Hat tip to @sjorford .

**Comment by PeteDevoy** [comment]
Awesome, that makes sense.

**Comment by PeteDevoy** [comment]
Just for completeness, the withdrawn are:
* E14000593 - Diane Scott - Green
* E14000613 - Paul Hopfensperger - Independent
