### ISSUE TITLE
'Add a link to [a SOPN]' links to old GE spreadsheet of SOPNs

### ISSUE THREAD

**Issue by JoeMitchell** [DemocracyClub/yournextrepresentative#305]
![image](https://user-images.githubusercontent.com/8096305/30924853-e143dbac-a3a7-11e7-8948-a70512ae4653.png)

If I click the top link (_help us by uploading..._) that's cool, but the _'Add a link to one'_ on the right-hand-side menu goes through to the GE SOPN [spreadsheet](https://docs.google.com/spreadsheets/d/1wZeniqnMi1dyuB1eqCCumUq1kp8O_57TQsLyPwmLtQc/edit)

**Comment by andylolz** [comment]
Could/should these one-off, time-sensitive links live in config.py or somewhere like that? So that they’re a bit more obvious && easy to change? This one’s buried in a template currently:
https://github.com/DemocracyClub/yournextrepresentative/blob/8992a1b5296b347c50c70caf41a23090f2bfa5e1/elections/uk/templates/uk/data_timeline.html#L24-L25

**Comment by chris48s** [comment]
I think the ideal solution would be if this link was stored in the database against the election group id.

* For major scheduled elections, we can set a google doc url against ids like `local.2017-05-04` and `parl.2017-06.08` (via a form in `/admin`)
* For minor by-election groups (e.g: `local.2017-10-05`) where we aren't running a sheet, the value can be `null`
* Some logic in the template can just not show/hide this link as applicable.

**Comment by chris48s** [comment]
does #792 completely resolve this, or is there still stuff left to do on this issue?
