### ISSUE TITLE
Deletion/merging of candidates

### ISSUE THREAD

**Issue by fabianhoward** [DemocracyClub/yournextrepresentative#316]
Sometimes the same person is created twice as two different candidates:

Example:
  https://candidates.democracyclub.org.uk/person/34877
  https://candidates.democracyclub.org.uk/person/1224

There does not seem to exist tooling on the site to deal with this either by merging them together or being able to delete on in it's entirety. I believe this would be desirable to have as feature.

**Comment by symroe** [comment]
Thanks for reporting @fabianhoward!

We do have a merge feature, but only people with permission are allowed to use it. This is to prevent accidental merging – something that is hard to undo.

I'll merge them now, but we should make a note to add some sort of "suggest a merge" feature, so that you don't have to make a github issue for each duplicate. 

How did you find this one, by the way?

**Comment by symroe** [comment]
I've merged 34877 in to 1224 now, so will close this issue.

I've made a new issue for the flagging duplicates feature:
https://github.com/DemocracyClub/yournextrepresentative/issues/317

Thanks again for reporting!

**Comment by fabianhoward** [comment]
Many thanks. We're ingesting your data to help journalists understand what candidates are saying, and we require that each twitter username is unique which was violated in this case.

**Comment by symroe** [comment]
Great – and that's a good (and obvious!) check for duplicates.

Thanks for reporting, and feel free to [join our Slack](https://slack.democracyclub.org.uk/) if it's easier to chat there.
