### ISSUE TITLE
"Locking disabled" message shows when I've not suggested a lock

### ISSUE THREAD

**Issue by gregorywilliams** [DemocracyClub/yournextrepresentative#443]
The "Locking disabled because you suggested locking this post. Someone else will double check it soon." appears to currently be shown on all elections even though I've not suggested a lock. For example:

An unlocked one:
https://candidates.democracyclub.org.uk/election/local.west-berkshire.2018-04-19/post/UTW:E05002315/thatcham-west

An already-locked one:
https://candidates.democracyclub.org.uk/election/local.south-northamptonshire.2018-04-12/post/DIW:E05006044/middleton-cheney

**Comment by chris48s** [comment]
screenshot from prod:

![screenshot at 2018-03-26 16 48 15](https://user-images.githubusercontent.com/6025893/37917367-26add7d2-3116-11e8-9777-2fa7dfbc1463.png)

Also, there is a stray quote character on the lock/unlock buttons:

![screenshot at 2018-03-26 16 54 04](https://user-images.githubusercontent.com/6025893/37917434-54dbff08-3116-11e8-99fa-01c06068525e.png)

I'd submit a PR but will probs just conflict with the fix for this
