### ISSUE TITLE
Require two people to verify a post before locking

### ISSUE THREAD

**Issue by sjorford** [DemocracyClub/yournextrepresentative#524]
Currently it is possible for a post to be locked by the same person who enters the candidates - the lock function should not be available until somebody else has suggested locking it.

e.g. https://candidates.democracyclub.org.uk/election/local.cherwell.2018-06-21/post/DIW:E05010928/bicester-west - one user added all the candidates individually (without using the bulk entry form) and locked the post themselves.

**Comment by chris48s** [comment]
Additionally, we should validate presence of a SOPN: It should not be valid to either lock or suggest a lock if there is no SOPN associated with the ballot (PEE) yet.

**Comment by jf1** [comment]
> we should validate presence of a SOPN

This could be handled by a system of 'stages' that each post must progress through sequentially, ie rather than create a `does_this_post_have_a_SoPN` variable (and many more) use something like `post_status_within_dc` that progresses from `0 - expected` through something like: election announced, SoPN published, all candidates entered, post locked, election day, polls closed, results recorded, results verified.

**Comment by symroe** [comment]
Agree with J that there is a better way to do this, but @chris48s's work fixes the issue for now without having to refactor other things (they are being refactored in other work already!).

Will call _this_ issue closed, and consider a better workflow concept in future work.
