### ISSUE TITLE
Upcoming elections table shows number of candidates per election, not per ward

### ISSUE THREAD

**Issue by sjorford** [DemocracyClub/yournextrepresentative#531]
e.g. the two Basildon by-elections have 4 and 3 candidates respectively, but the table shows 7 each:

![image](https://user-images.githubusercontent.com/10633357/41529845-5644414a-72e6-11e8-9e19-900592fd373b.png)

Possibly related: the links in both the Election and Area columns go to the /constituencies page - the latter should go to the /post page

**Comment by chris48s** [comment]
I expect I want to wait until the work on the [2018-refactor](https://github.com/DemocracyClub/yournextrepresentative/compare/2018-refactor) branch hits `master` before looking at this one otherwise we'll end up fixing the same bug twice.

/remind @chris48s ping in 2 weeks

**Comment by chris48s** [comment]
I put this off for ages because we were moving so much about. Finally went to reproduce it today and it works fine now:

![screenshot at 2018-09-28 16-23-50](https://user-images.githubusercontent.com/6025893/46218388-5cf7d500-c33c-11e8-8216-89a9ae985122.png)

I reckon this got fixed somewhere in the depths of https://github.com/DemocracyClub/yournextrepresentative/commit/7054bcb5c41a911091cded02dbe60ec56603b4e4

I've submitted #657 to change the link target on the post. Do re-open or raise another issue if this happens again.
