### ISSUE TITLE
Improve SOPN parsing when >1 pages have the same header

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/yournextrepresentative#882]
SOPN parser only picks up the first page of candidates on this SOPN
https://candidates.democracyclub.org.uk/elections/local.york.strensall.2019-05-02/sopn/

**Comment by jf1** [comment]
There's also no warning about the existence of the second page when moderating at https://candidates.democracyclub.org.uk/moderation/suggest-lock/?pdfembed=1

**Comment by VirginiaDooley** [comment]
I think the problem is that `detect_top_page` is returning `True` for all pages so the second page never gets appended properly. I think the issue is [here](https://github.com/DemocracyClub/yournextrepresentative/blob/2784194433e6521a5e3354bef8294d7c76f2d485/ynr/apps/sopn_parsing/helpers/pdf_helpers.py#L126), but not yet exactly sure what the fix should be.
