### ISSUE TITLE
Delete internal identifier when user changes twitter username

### ISSUE THREAD

**Issue by sjorford** [DemocracyClub/yournextrepresentative#949]
https://candidates.democracyclub.org.uk/person/69954

Candidate was imported from 2014 YourNextMEP data, with twitter handle of ClaudeMoraesMEP - but since 2014 this handle has been taken over by someone else.

In version 2c2f30e99470d2e1 I changed the handle to Claude_Moraes, but then overnight Twitter changed it back to ClaudeMoraesMEP.

I then deleted the Twitter handle, which seems to have deleted the Twitter ID as well (version 6e1b4fb42fff7f2b) and then re-added the correct handle, which hopefully will now stick.

**Comment by symroe** [comment]
Thanks! Yes, of course twitterbot doesn't know the difference between the screen name changing on Twitter and because a user corrected it, but not the internal id.

It's a rare case, as twitterbot will normally catch screen name changes a) before a user and b) before another valid account is set up, but it's worth fixing
