### ISSUE TITLE
Results Entry: Show candidates in ballot paper order 

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/yournextrepresentative#996]
> example of candidate ordering https://candidates.democracyclub.org.uk/uk_results/local.torridge.bideford-east.2019-05-02/
> The PDF has De Freyne-Martin before Dezart, but our results page has it the other way round (presumably because it is not including "De" as part of the surname)

> and in this case the two Taylors are the wrong way round (Debbie before Carl) https://candidates.democracyclub.org.uk/uk_results/local.brighton-and-hove.goldsmid.2019-05-02/

When the results entry shows the candidates in an order which is close to ballot paper order but with 2 candidates transposed, this can sometimes lead to results being transposed at data entry time.

**Comment by symroe** [comment]
This is always going to be imperfect, because names, and the fact that sometimes there isn't a sort order that everyone will agree on.

Given that, there are a couple of options:

1. In https://github.com/DemocracyClub/yournextrepresentative/pull/990/commits/efcd713c4d731df6572b5f732aed3eebf0bbf127 I added a "LastWord" DB transformation. This allows sorting on the last word in a field (See above about names being complex and this not being ideal).

2. We also have a `sort_name` field on `Person` that isn't exposed anywhere, but could be. 

The combination of  1 and 2 means we can start to sort `Memberships` on `["person__sort_name", "last_name"]` (as I do in https://github.com/DemocracyClub/yournextrepresentative/pull/990/commits/3ce3a88ba55ada53c9d54698fd59df862c155b1f)

I guess an initial improvement is to ensure that we sort the results entry form the same way as we sort the ballot page.

**Comment by chris48s** [comment]
Yeah "LastWord" is all fun and games until someone is Sym van Roe, or Sym de Roe, or whatever..

It feels like in order to do this in an exactly reliable way, we'd need to actually collect the sort position from the SOPN and store it on the membership as an extra data point in bulk entry or something, which probably creates other problems. Exposing 'sort name' and using it consistently sounds like it would be a good tradeoff/get us most of the way there.
